services:
  - type: web
    name: replicache-quickstarts-todo
    env: node
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    buildCommand: "npm install && npm run build" # optional (defaults to Dockerfile command)
    startCommand: "npm run prod --ws"
    numInstances: 1 # optional (defaults to 1)
    envVars:
      - key: VITE_REPLICACHE_LICENSE_KEY 
        value: l10d16dd3dd8d47599542a66355649688

      - key: NODE_VERSION
        value: 16.15.1
      - key: DATABASE_URL
        fromDatabase:
          name: replicache-todo
          property: connectionString

databases:
  - name: replicache-todo
    databaseName: db
